data_root: '/local/home/lhauptmann/CV4A/data/raw'
data_split: '/local/home/lhauptmann/CV4A/data/raw/FieldIds.csv'
batch_size: 16
num_classes: 8
gru_hidden_size: 256
gru_num_layers: 2
dropout: 0.5
lr: 1e-3
lr_step: 10
lr_gamma: 0.7
num_epochs: 30
seed: 10
output_dir: '/local/home/lhauptmann/CV4A/CPrediction/output'